"""Tests for the board map (src/ingestion/board_map.py): the YAML file and the
pure functions over it. No network."""

from datetime import datetime

import pytest
import yaml

from src.config import (
    AshbySource,
    Config,
    ConfigError,
    GreenhouseSource,
    LeverSource,
    WorkableSource,
    WorkdaySource,
)
from src.ingestion import board_map as bm
from src.ingestion.board_map import BoardMap, CheckResult

NOW = datetime(2026, 10, 4, 3, 0, 0)
LATER = datetime(2026, 10, 20, 3, 0, 0)

GH = GreenhouseSource(type="greenhouse", board="acme")
LV = LeverSource(type="lever", company="acme")
WD = WorkdaySource(type="workday", tenant="cba", datacenter="wd3", site="CommBank_Careers")


def _live(source, postings=10, matched=2):
    return CheckResult(source, live=True, postings=postings, matched=matched)


def _dead(source):
    return CheckResult(source, live=False)


def _company(board_map, name):
    return board_map.find_company(name)


# --- file: load and save -----------------------------------------------------


def test_round_trip_through_save_and_load(tmp_path):
    path = str(tmp_path / "map.yaml")
    original = bm.merge_check(BoardMap(), "Acme", [_live(GH), _live(WD, 167, 8)], NOW)
    bm.save_map(original, path)
    assert bm.load_map(path) == original


def test_a_missing_file_is_an_empty_map(tmp_path):
    assert bm.load_map(str(tmp_path / "nope.yaml")) == BoardMap()


def test_save_creates_the_folder_and_leaves_no_temp_file(tmp_path):
    path = tmp_path / "data" / "map.yaml"
    bm.save_map(BoardMap(), str(path))
    assert path.exists()
    assert [p.name for p in path.parent.iterdir()] == ["map.yaml"]


def test_names_and_tokens_yaml_could_misread_come_back_as_the_same_strings(tmp_path):
    path = str(tmp_path / "map.yaml")
    tricky = ["No", "On", "null", "123", "yes", "2026-10-04"]
    board_map = BoardMap()
    for name in tricky:
        source = LeverSource(type="lever", company=name)
        board_map = bm.merge_check(board_map, name, [_live(source)], NOW)
    bm.save_map(board_map, path)

    loaded = bm.load_map(path)
    assert [c.name for c in loaded.companies] == tricky
    assert [c.boards[0].line for c in loaded.companies] == [f"lever {n}" for n in tricky]
    assert all(isinstance(c.name, str) for c in loaded.companies)
    # Every one of these is also quoted in the file, not written bare.
    for line in open(path, encoding="utf-8").read().splitlines():
        if line.strip().startswith("- name:") or line.strip().startswith("name:"):
            value = line.split(":", 1)[1].strip()
            assert yaml.safe_load(value) == value.strip("'\"")


def test_times_come_back_as_strings(tmp_path):
    path = str(tmp_path / "map.yaml")
    bm.save_map(bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW), path)
    company = bm.load_map(path).companies[0]
    assert company.checked_at == "2026-10-04T03:00:00"
    assert company.boards[0].first_seen == "2026-10-04T03:00:00"
    assert company.boards[0].last_live == "2026-10-04T03:00:00"


def test_an_unquoted_hand_edited_time_is_accepted_as_a_string(tmp_path):
    path = tmp_path / "map.yaml"
    path.write_text(
        "version: 1\n"
        "companies:\n"
        "- name: Acme\n"
        "  checked_at: 2026-10-04T03:00:00\n"
        "  boards:\n"
        "  - line: greenhouse acme\n"
        "    status: live\n"
        "    first_seen: 2026-10-04T03:00:00\n"
        "    last_miss_on: 2026-10-03\n",
        encoding="utf-8",
    )
    # safe_load really does turn these into datetime / date objects.
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(raw["companies"][0]["checked_at"], datetime)
    company = bm.load_map(str(path)).companies[0]
    assert company.checked_at == "2026-10-04T03:00:00"
    assert company.boards[0].first_seen == "2026-10-04T03:00:00"
    assert company.boards[0].last_miss_on == "2026-10-03"


def test_the_saved_file_starts_with_the_generated_comment(tmp_path):
    path = tmp_path / "map.yaml"
    bm.save_map(BoardMap(), str(path))
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by `python -m src.ingestion.resolve`. Do not edit")
    assert "version: 1" in text and "companies: []" in text


def test_save_replaces_an_existing_file_and_drops_hand_added_comments(tmp_path):
    path = tmp_path / "map.yaml"
    bm.save_map(BoardMap(), str(path))
    path.write_text(path.read_text(encoding="utf-8") + "# my note\n", encoding="utf-8")
    bm.save_map(bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW), str(path))
    assert "my note" not in path.read_text(encoding="utf-8")


def test_a_failed_save_leaves_the_old_file_alone(tmp_path, monkeypatch):
    path = tmp_path / "map.yaml"
    bm.save_map(bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW), str(path))
    before = path.read_text(encoding="utf-8")

    def boom(*args, **kwargs):
        raise OSError("disk gone")

    monkeypatch.setattr(bm.os, "replace", boom)
    with pytest.raises(OSError):
        bm.save_map(BoardMap(), str(path))
    assert path.read_text(encoding="utf-8") == before
    assert [p.name for p in tmp_path.iterdir()] == ["map.yaml"]  # temp file cleaned up


@pytest.mark.parametrize(
    "body, fragment",
    [
        ("- just\n- a list\n", "must be a mapping"),
        ("version: 1\n", "'companies' list"),
        ("version: 1\ncompanies: nope\n", "'companies' list"),
        ("version: 2\ncompanies: []\n", "unsupported version"),
        ("companies:\n- nonsense\n", "companies[0] must be a mapping"),
        ("companies: [\n", "not valid YAML"),
    ],
)
def test_a_malformed_file_raises_a_config_error(tmp_path, body, fragment):
    path = tmp_path / "map.yaml"
    path.write_text(body, encoding="utf-8")
    with pytest.raises(ConfigError, match=fragment.replace("[", r"\[").replace("]", r"\]")):
        bm.load_map(str(path))


def test_an_unknown_status_names_the_company(tmp_path):
    path = tmp_path / "map.yaml"
    path.write_text(
        "companies:\n- name: Acme\n  boards:\n"
        "  - line: greenhouse acme\n    status: sleeping\n    first_seen: x\n",
        encoding="utf-8",
    )
    with pytest.raises(ConfigError) as exc:
        bm.load_map(str(path))
    assert "'Acme'" in str(exc.value) and "status" in str(exc.value)


def test_an_unparseable_line_names_the_company_and_the_line(tmp_path):
    path = tmp_path / "map.yaml"
    path.write_text(
        "companies:\n- name: Acme\n  boards:\n"
        "  - line: taleo acme\n    status: live\n    first_seen: x\n",
        encoding="utf-8",
    )
    with pytest.raises(ConfigError) as exc:
        bm.load_map(str(path))
    assert "'Acme'" in str(exc.value) and "taleo acme" in str(exc.value)


def test_a_company_name_that_is_not_text_is_rejected(tmp_path):
    path = tmp_path / "map.yaml"
    path.write_text("companies:\n- name: 123\n", encoding="utf-8")
    with pytest.raises(ConfigError, match="name"):
        bm.load_map(str(path))


# --- merge_check -------------------------------------------------------------


def test_a_new_live_board_is_recorded():
    result = bm.merge_check(BoardMap(), "Acme", [_live(GH, 12, 3)], NOW)
    company = _company(result, "Acme")
    assert company.checked_at == "2026-10-04T03:00:00" and company.needs_check is False
    board = company.boards[0]
    assert (board.line, board.status) == ("greenhouse acme", "live")
    assert (board.postings, board.matched, board.misses) == (12, 3, 0)
    assert board.first_seen == board.last_live == "2026-10-04T03:00:00"


def test_a_live_board_with_no_postings_is_empty():
    result = bm.merge_check(BoardMap(), "Acme", [_live(GH, 0, 0)], NOW)
    board = _company(result, "Acme").boards[0]
    assert board.status == "empty"
    assert board.last_live is None
    assert bm.live_sources(result) == []  # not scraped


def test_a_dead_board_that_was_never_in_the_map_is_not_recorded():
    result = bm.merge_check(BoardMap(), "Acme", [_dead(GH), _live(LV)], NOW)
    assert [b.line for b in _company(result, "Acme").boards] == ["lever acme"]


def test_a_company_with_no_boards_is_still_recorded_as_checked():
    result = bm.merge_check(BoardMap(), "Acme", [_dead(GH)], NOW)
    company = _company(result, "Acme")
    assert company.boards == [] and company.checked_at is not None


def test_a_live_board_that_dies_becomes_gone_and_is_kept():
    first = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    second = bm.merge_check(first, "Acme", [_dead(GH)], LATER)
    board = _company(second, "Acme").boards[0]
    assert board.status == "gone"
    assert board.first_seen == "2026-10-04T03:00:00"
    assert board.last_live == "2026-10-04T03:00:00"  # when it was last seen alive
    assert bm.live_sources(second) == []


def test_a_gone_board_that_comes_back_is_live_again():
    gone = bm.merge_check(
        bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW), "Acme", [_dead(GH)], NOW
    )
    back = bm.merge_check(gone, "Acme", [_live(GH, 5, 1)], LATER)
    board = _company(back, "Acme").boards[0]
    assert board.status == "live" and board.postings == 5
    assert board.first_seen == "2026-10-04T03:00:00"
    assert board.last_live == "2026-10-20T03:00:00"
    assert len(_company(back, "Acme").boards) == 1  # not duplicated


def test_a_gone_board_stays_gone_when_still_dead():
    gone = bm.merge_check(
        bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW), "Acme", [_dead(GH)], NOW
    )
    again = bm.merge_check(gone, "Acme", [_dead(GH)], LATER)
    assert _company(again, "Acme").boards[0].status == "gone"


def test_a_live_board_resets_the_miss_counters():
    first = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    board = _company(first, "Acme").boards[0]
    board.misses, board.last_miss_on = 2, "2026-10-03"
    again = bm.merge_check(first, "Acme", [_live(GH)], LATER)
    board = _company(again, "Acme").boards[0]
    assert (board.misses, board.last_miss_on) == (0, None)


def test_needs_check_is_cleared():
    first = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    _company(first, "Acme").needs_check = True
    again = bm.merge_check(first, "Acme", [_live(GH)], LATER)
    assert _company(again, "Acme").needs_check is False
    assert _company(again, "Acme").checked_at == "2026-10-20T03:00:00"


def test_all_live_boards_are_kept_not_just_the_first():
    result = bm.merge_check(BoardMap(), "Acme", [_live(GH), _live(LV), _dead(WD)], NOW)
    assert [b.line for b in _company(result, "Acme").boards] == [
        "greenhouse acme", "lever acme",
    ]


def test_a_board_is_matched_regardless_of_token_case():
    first = bm.merge_check(BoardMap(), "Acme", [_live(WorkableSource(type="workable", account="Acme"))], NOW)
    again = bm.merge_check(first, "Acme", [_live(WorkableSource(type="workable", account="acme"))], LATER)
    assert len(_company(again, "Acme").boards) == 1


def test_merge_check_does_not_change_its_input():
    original = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    snapshot = original.model_copy(deep=True)
    bm.merge_check(original, "Acme", [_dead(GH)], LATER)
    bm.merge_check(original, "Other", [_live(LV)], LATER)
    assert original == snapshot


def test_company_lookup_ignores_case():
    result = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    again = bm.merge_check(result, "ACME", [_live(GH)], LATER)
    assert len(again.companies) == 1


# --- drop, due, live ---------------------------------------------------------


def test_a_company_removed_from_the_file_is_dropped():
    board_map = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    board_map = bm.merge_check(board_map, "Other", [_live(LV)], NOW)
    kept = bm.drop_missing_companies(board_map, ["acme"])
    assert [c.name for c in kept.companies] == ["Acme"]
    assert [c.name for c in board_map.companies] == ["Acme", "Other"]  # input untouched


def test_is_due():
    board_map = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    company = _company(board_map, "Acme")
    assert bm.is_due(None, NOW, 14) is True  # not in the map yet
    assert bm.is_due(company, NOW, 14) is False
    assert bm.is_due(company, datetime(2026, 10, 18, 3, 0, 0), 14) is False  # exactly 14 days
    assert bm.is_due(company, datetime(2026, 10, 18, 3, 0, 1), 14) is True  # older than 14
    company.needs_check = True
    assert bm.is_due(company, NOW, 14) is True
    company.needs_check, company.checked_at = False, None
    assert bm.is_due(company, NOW, 14) is True  # never checked
    company.checked_at = "garbage"
    assert bm.is_due(company, NOW, 14) is True


def test_is_due_with_a_timezone_aware_hand_edited_time():
    board_map = bm.merge_check(BoardMap(), "Acme", [_live(GH)], NOW)
    company = _company(board_map, "Acme")
    company.checked_at = "2026-10-04T03:00:00+00:00"
    assert bm.is_due(company, NOW, 14) is False


def test_live_sources_lists_only_live_boards():
    board_map = bm.merge_check(BoardMap(), "Acme", [_live(GH), _live(LV, 0, 0)], NOW)
    board_map = bm.merge_check(board_map, "Bank", [_live(WD)], NOW)
    assert bm.live_sources(board_map) == [GH, WD]


# --- Config.resolved_sources -------------------------------------------------


def _config(tmp_path, *, companies=True, sources=None, map_boards=()):
    map_path = str(tmp_path / "board_map.yaml")
    board_map = BoardMap()
    for name, source in map_boards:
        board_map = bm.merge_check(board_map, name, [_live(source)], NOW)
    bm.save_map(board_map, map_path)
    raw = {"board_map_file": map_path}
    if companies:
        raw["companies_file"] = "companies.txt"
    raw["sources"] = sources if sources is not None else [{"type": "adzuna", "country": "au"}]
    return Config.model_validate(raw)


def test_resolved_sources_merges_pinned_and_mapped(tmp_path):
    cfg = _config(tmp_path, map_boards=[("Acme", GH)])
    assert cfg.pinned_sources == [cfg.sources[0]]
    assert cfg.resolved_sources == [cfg.sources[0], GH]


def test_a_pinned_board_wins_over_a_mapped_one(tmp_path):
    pinned = [{"type": "greenhouse", "board": "ACME"}]
    cfg = _config(tmp_path, sources=pinned, map_boards=[("Acme", GH)])
    resolved = cfg.resolved_sources
    assert len(resolved) == 1
    assert resolved[0].board == "ACME"  # the pinned source, token as written


def test_a_pinned_workday_site_and_a_mapped_site_of_one_tenant_collapse(tmp_path):
    other_site = WorkdaySource(type="workday", tenant="CBA", datacenter="wd3", site="Other")
    pinned = [
        {"type": "workday", "tenant": "cba", "datacenter": "wd3", "site": "CommBank_Careers"}
    ]
    cfg = _config(tmp_path, sources=pinned, map_boards=[("CBA", other_site)])
    resolved = cfg.resolved_sources
    assert len(resolved) == 1 and resolved[0].site == "CommBank_Careers"


def test_two_companies_mapping_to_one_board_give_one_source(tmp_path):
    cfg = _config(tmp_path, map_boards=[("Acme", GH), ("Acme Pty Ltd", GH)])
    assert cfg.resolved_sources.count(GH) == 1


def test_a_missing_map_adds_nothing(tmp_path):
    cfg = Config.model_validate(
        {
            "companies_file": "companies.txt",
            "board_map_file": str(tmp_path / "absent.yaml"),
            "sources": [{"type": "adzuna", "country": "au"}],
        }
    )
    assert cfg.resolved_sources == cfg.pinned_sources


def test_with_companies_file_unset_the_map_is_ignored_even_if_it_exists(tmp_path):
    cfg = _config(tmp_path, companies=False, map_boards=[("Acme", GH)])
    assert (tmp_path / "board_map.yaml").exists()
    assert cfg.resolved_sources == cfg.pinned_sources
    assert all(s.type == "adzuna" for s in cfg.resolved_sources)


def test_mapped_sources_keep_their_token_exactly_as_written(tmp_path):
    source = AshbySource(type="ashby", org="Amp-Co")
    cfg = _config(tmp_path, map_boards=[("Amp", source)])
    assert cfg.resolved_sources[-1].org == "Amp-Co"
