"""The board map: where each company's boards were found (plans/05).

`data/board_map.yaml` is generated state that `make resolve` rewrites. It is
read and written only here, through `load_map()` and `save_map()`, so the YAML
rules live in one place:

- Written with `yaml.safe_dump` and read with `yaml.safe_load`. `safe_dump`
  quotes any string YAML would read as something else (`no`, `on`, `null`,
  `123`), so tokens and names survive a round trip as strings. The file is never
  built by string formatting.
- Times are naive UTC ISO strings, like the database columns. A hand-edited,
  unquoted time loads as a `datetime`; the loader accepts it and normalises it.
- Comments and layout do not survive a save. Anything to keep goes in
  companies.txt.
- A file that is not shaped right raises a `ConfigError` naming the entry. A
  missing file is an empty map.
- Saved through a temporary file and `os.replace()`, so an interrupted run
  cannot leave half a file.

The rest of the module is pure functions over the map (`merge_check`,
`is_due`, ...) so they can be tested without a network or a file.
"""

import copy
import os
import tempfile
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Collection, List, Literal, Optional, Tuple, Union

import requests
import yaml
from pydantic import BaseModel, Field, ValidationError, field_validator

from src.config import ConfigError, Source, source_from_text, source_key, source_to_line

MAP_VERSION = 1

# An HTTP status that says "this board is not here" (as opposed to "I could not
# ask"): gone (404, 410) or an unknown tenant (Workday answers 422).
DEFINITE_MISS_STATUSES = (404, 410, 422)

# (source type, lower-cased token): what a planned scrape reports as its board
# (`PlannedScrape.board`) and what `source_key()` returns.
BoardKey = Tuple[str, str]
# What one board scrape came to: the number of postings it returned, or the
# exception it raised.
Outcome = Union[int, BaseException]

HEADER = (
    "# Generated by `python -m src.ingestion.resolve`. Do not edit: it is rewritten\n"
    "# on every run. Put names, aliases and block lines in companies.txt instead.\n"
)

Status = Literal["live", "empty", "gone"]


def _naive_utc(moment: datetime) -> datetime:
    """An aware time (only a hand-edited file can hold one) converted to naive UTC."""
    if moment.tzinfo is not None:
        return moment.astimezone(timezone.utc).replace(tzinfo=None)
    return moment


def format_time(moment: datetime) -> str:
    """A time as the naive UTC string the map stores."""
    return _naive_utc(moment).replace(microsecond=0).isoformat()


def _as_time_string(value: Any) -> Any:
    """Accept a `datetime` or `date` (an unquoted hand-edited value) as a string."""
    if isinstance(value, datetime):
        return format_time(value)
    if isinstance(value, date):
        return value.isoformat()
    return value


class BoardEntry(BaseModel):
    """One board a company was found on."""

    line: str  # a sources-file line: `source_to_line()` writes it, `source_from_text()` reads it
    status: Status
    postings: int = 0
    matched: int = 0
    first_seen: str
    last_live: Optional[str] = None
    misses: int = 0
    last_miss_on: Optional[str] = None  # 'YYYY-MM-DD' of the last counted miss

    @field_validator("first_seen", "last_live", "last_miss_on", mode="before")
    @classmethod
    def _times_as_text(cls, value: Any) -> Any:
        return _as_time_string(value)

    @property
    def source(self) -> Source:
        return source_from_text(self.line, where=f"board line {self.line!r}")


class CompanyEntry(BaseModel):
    name: str
    checked_at: Optional[str] = None
    needs_check: bool = False
    boards: List[BoardEntry] = Field(default_factory=list)

    @field_validator("checked_at", mode="before")
    @classmethod
    def _time_as_text(cls, value: Any) -> Any:
        return _as_time_string(value)

    @field_validator("name", mode="before")
    @classmethod
    def _name_is_text(cls, value: Any) -> Any:
        # A name YAML read as a number or boolean is a hand-edit gone wrong;
        # say so rather than quietly turning it into a string.
        if not isinstance(value, str):
            raise ValueError("name must be text")
        return value

    def find_board(self, source: Source) -> Optional[BoardEntry]:
        """This company's entry for `source`, matched by `source_key()`."""
        wanted = source_key(source)
        for board in self.boards:
            if source_key(board.source) == wanted:
                return board
        return None


class BoardMap(BaseModel):
    companies: List[CompanyEntry] = Field(default_factory=list)

    def find_company(self, name: str) -> Optional[CompanyEntry]:
        wanted = name.strip().lower()
        for company in self.companies:
            if company.name.lower() == wanted:
                return company
        return None


@dataclass
class CheckResult:
    """The outcome of checking one candidate board."""

    source: Source
    live: bool  # the board answered; False when it raised (404 and the like)
    postings: int = 0
    matched: int = 0
    # Dead, but not because the board is missing: a timeout, a connection error
    # or a server error says nothing about whether the board exists.
    inconclusive: bool = False


# ---------------------------------------------------------------------------
# File: load and save
# ---------------------------------------------------------------------------


def load_map(path: str) -> BoardMap:
    """Read the map. A missing file is an empty map; a malformed one raises a
    `ConfigError` that names the entry."""
    p = Path(path)
    if not p.exists():
        return BoardMap()
    try:
        raw = yaml.safe_load(p.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ConfigError(f"{path} is not valid YAML:\n{exc}") from exc

    if not isinstance(raw, dict) or not isinstance(raw.get("companies"), list):
        raise ConfigError(
            f"{path} must be a mapping with a 'companies' list; delete it and run "
            "`make resolve` to rebuild it"
        )
    version = raw.get("version", MAP_VERSION)
    if version != MAP_VERSION:
        raise ConfigError(f"{path}: unsupported version {version!r} (expected {MAP_VERSION})")

    companies: List[CompanyEntry] = []
    for index, item in enumerate(raw["companies"]):
        label = f"{path}: companies[{index}]"
        if not isinstance(item, dict):
            raise ConfigError(f"{label} must be a mapping")
        if isinstance(item.get("name"), str):
            label += f" ({item['name']!r})"
        try:
            entry = CompanyEntry.model_validate(item)
        except ValidationError as exc:
            problems = "; ".join(
                f"{'.'.join(str(part) for part in err['loc'])}: {err['msg']}"
                for err in exc.errors()
            )
            raise ConfigError(f"{label} is invalid: {problems}") from exc
        for board in entry.boards:
            try:
                source = board.source
            except ConfigError as exc:
                raise ConfigError(
                    f"{label}: board line {board.line!r} is not a valid board line"
                ) from exc
            if source.type == "adzuna":
                raise ConfigError(f"{label}: board line {board.line!r} is not a board")
        companies.append(entry)
    return BoardMap(companies=companies)


def save_map(board_map: BoardMap, path: str) -> None:
    """Write the map through a temporary file in the same directory."""
    document = {
        "version": MAP_VERSION,
        "companies": [company.model_dump() for company in board_map.companies],
    }
    text = HEADER + yaml.safe_dump(
        document, sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=target.parent, prefix=f".{target.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        os.replace(tmp_name, target)
    except BaseException:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
        raise


# ---------------------------------------------------------------------------
# Pure functions over the map
# ---------------------------------------------------------------------------


def live_sources(board_map: BoardMap) -> List[Source]:
    """The boards to scrape: every `live` board of every company."""
    return [
        board.source
        for company in board_map.companies
        for board in company.boards
        if board.status == "live"
    ]


def is_due(
    company: Optional[CompanyEntry], now: datetime, recheck_days: int
) -> bool:
    """Does this company need checking? True when it is not in the map yet, is
    flagged `needs_check`, was never checked, or was last checked more than
    `recheck_days` ago. The one place that rule lives (how often to recheck is a
    decision for the later maintenance cycle)."""
    if company is None or company.needs_check or not company.checked_at:
        return True
    try:
        checked = _naive_utc(datetime.fromisoformat(company.checked_at))
    except ValueError:
        return True  # an unreadable time is as good as never checked
    return _naive_utc(now) - checked > timedelta(days=recheck_days)


def drop_missing_companies(board_map: BoardMap, names: List[str]) -> BoardMap:
    """The map without entries for companies no longer listed in companies.txt."""
    wanted = {name.strip().lower() for name in names}
    return BoardMap(
        companies=[
            copy.deepcopy(c) for c in board_map.companies if c.name.lower() in wanted
        ]
    )


def merge_check(
    board_map: BoardMap, company: str, results: List[CheckResult], now: datetime
) -> BoardMap:
    """The map after checking `company`'s candidate boards (the input is not
    changed).

    - a live board with postings is `live`; live with none is `empty`;
    - a board already in the map that is now dead becomes `gone`, and one that
      is already `gone` stays so;
    - a dead board that was never in the map is not recorded;
    - an inconclusive failure (see `CheckResult`) changes nothing for that board;
    - the company's `needs_check` is cleared and `checked_at` set.
    """
    updated = copy.deepcopy(board_map)
    stamp = format_time(now)
    entry = updated.find_company(company)
    if entry is None:
        entry = CompanyEntry(name=company)
        updated.companies.append(entry)

    for result in results:
        board = entry.find_board(result.source)
        if result.live:
            status: Status = "live" if result.postings > 0 else "empty"
            if board is None:
                board = BoardEntry(
                    line=source_to_line(result.source), status=status, first_seen=stamp
                )
                entry.boards.append(board)
            board.status = status
            board.postings = result.postings
            board.matched = result.matched
            if status == "live":
                board.last_live = stamp
                board.misses = 0
                board.last_miss_on = None
        elif board is not None and not result.inconclusive:
            board.status = "gone"
            board.postings = 0
            board.matched = 0

    entry.needs_check = False
    entry.checked_at = stamp
    return updated


def is_definite_miss(outcome: Outcome) -> bool:
    """Does this scrape outcome say the board is not there?

    Definite: a scrape that returned no postings, or an HTTP 404, 410 or 422
    (`http_util` re-raises a 4xx at once, with its response attached).
    Everything else says nothing about whether the board exists: a timeout, a
    connection error, a 5xx (after the retries), a scraper's own error such as
    `WorkdayError` (a capped or inconsistent list), and a scrape that returned
    postings.
    """
    if isinstance(outcome, BaseException):
        if isinstance(outcome, requests.HTTPError):
            status = getattr(outcome.response, "status_code", None)
            return status in DEFINITE_MISS_STATUSES
        return False
    return outcome == 0


def apply_scrape_outcomes(
    board_map: BoardMap,
    outcomes: List[Tuple[BoardKey, Outcome]],
    stale_after: int,
    now: datetime,
    pinned: Collection[BoardKey] = (),
) -> Tuple[BoardMap, List[Source]]:
    """The map after a scrape, and the boards whose stored rows to retire (the
    input is not changed).

    For each mapped (`live`) board that was scraped:
    - postings returned: `misses` back to 0, `last_miss_on` cleared, `last_live`
      and `postings` updated;
    - a definite miss (`is_definite_miss`): `misses` goes up by one, at most once
      per board per calendar day (UTC), so `stale_after` means that many
      separate days. At `stale_after` the board becomes `gone` and its company is
      flagged `needs_check`, so the next `make resolve` looks for it elsewhere;
    - anything else is not a miss: the counters are left alone.

    Pinned boards (`pinned`, as `source_key()` values) are never touched: they
    are your explicit choice, and a failing one is only logged by the scrape.
    """
    updated = copy.deepcopy(board_map)
    stamp = format_time(now)
    today = _naive_utc(now).date().isoformat()
    retire: List[Source] = []
    retired_keys = set()

    for (kind, token), outcome in outcomes:
        key = (kind, token.strip().lower())
        if key in pinned:
            continue
        for company in updated.companies:
            for board in company.boards:
                if board.status != "live" or source_key(board.source) != key:
                    continue
                if not isinstance(outcome, BaseException) and outcome > 0:
                    board.misses = 0
                    board.last_miss_on = None
                    board.last_live = stamp
                    board.postings = outcome
                elif is_definite_miss(outcome):
                    if board.last_miss_on != today:
                        board.misses += 1
                        board.last_miss_on = today
                    if board.misses >= stale_after:
                        board.status = "gone"
                        board.postings = 0
                        board.matched = 0
                        company.needs_check = True
                        if key not in retired_keys:
                            retired_keys.add(key)
                            retire.append(board.source)
    return updated, retire
